name: TileScanner
main: onim.en.tilescanner.TileScanner
version: 0.0.1
commands: 
  scantile:
    description: Scan tile block within area you specified.
    permission: onim.en.scantile
    usage: /<command> [x1,y1,z1] [x2,y2,z2]